INSERT INTO books (name, author, pages, samples) VALUES ('Poemas','Giacomo Leopardi',218,4);
INSERT INTO books (name, author, pages, samples) VALUES ('El cuaderno dorado','Doris Lessing',165,17);
INSERT INTO books (name, author, pages, samples) VALUES ('Pippi Calzaslargas','Astrid Lindgren',174,8);
INSERT INTO books (name, author, pages, samples) VALUES ('Diario de un loco','Lu Xun',268,5);
INSERT INTO books (name, author, pages, samples) VALUES ('Hijos de nuestro barrio','Naguib Mahfuz',152,10);
INSERT INTO books (name, author, pages, samples) VALUES ('Los Buddenbrook','Thomas Mann',141,17);
INSERT INTO books (name, author, pages, samples) VALUES ('La montaña mágica','Thomas Mann',245,20);
INSERT INTO books (name, author, pages, samples) VALUES ('Moby-Dick','Herman Melville',209,8);
INSERT INTO books (name, author, pages, samples) VALUES ('Ensayos','Michel de Montaigne',153,9);
INSERT INTO books (name, author, pages, samples) VALUES ('La historia','Elsa Morante',79,10);
INSERT INTO books (name, author, pages, samples) VALUES ('Beloved','Toni Morrison',164,17);
INSERT INTO books (name, author, pages, samples) VALUES ('Genji Monogatari','Murasaki Shikibu',87,5);
INSERT INTO books (name, author, pages, samples) VALUES ('El hombre sin atributos','Robert Musil',190,1);
INSERT INTO books (name, author, pages, samples) VALUES ('Lolita','Vladimir Nabokov',55,13);
INSERT INTO books (name, author, pages, samples) VALUES ('1984','George Orwell',92,0);
INSERT INTO books (name, author, pages, samples) VALUES ('Las metamorfosis','Ovidio',177,9);
INSERT INTO books (name, author, pages, samples) VALUES ('Libro del desasosiego','Fernando Pessoa',267,5);
INSERT INTO books (name, author, pages, samples) VALUES ('Cuentos','Edgar Allan Poe',282,9);
INSERT INTO books (name, author, pages, samples) VALUES ('En busca del tiempo perdido','Marcel Proust',159,17);
INSERT INTO books (name, author, pages, samples) VALUES ('Gargantúa y Pantagruel','François Rabelais',57,11);
INSERT INTO books (name, author, pages, samples) VALUES ('Pedro Páramo','Juan Rulfo',65,2);
INSERT INTO books (name, author, pages, samples) VALUES ('Masnavi','Rumi',86,11);
INSERT INTO books (name, author, pages, samples) VALUES ('Hijos de la medianoche','Salman Rushdie',136,20);
INSERT INTO books (name, author, pages, samples) VALUES ('Bostan','Saadi',78,2);
INSERT INTO books (name, author, pages, samples) VALUES ('Tiempo de migrar al norte','Tayeb Salih',140,9);
INSERT INTO books (name, author, pages, samples) VALUES ('Ensayo sobre la ceguera','José Saramago',227,4);
INSERT INTO books (name, author, pages, samples) VALUES ('Hamlet','William Shakespeare',229,13);
INSERT INTO books (name, author, pages, samples) VALUES ('El rey Lear','William Shakespeare',190,4);
INSERT INTO books (name, author, pages, samples) VALUES ('Otelo','William Shakespeare',275,14);
INSERT INTO books (name, author, pages, samples) VALUES ('Edipo rey','Sófocles',75,1);
INSERT INTO books (name, author, pages, samples) VALUES ('Rojo y negro','Stendhal',111,13);
INSERT INTO books (name, author, pages, samples) VALUES ('Vida y opiniones del caballero Tristram Shandy','Laurence Sterne',191,10);
INSERT INTO books (name, author, pages, samples) VALUES ('La conciencia de Zeno','Italo Svevo',234,19);
INSERT INTO books (name, author, pages, samples) VALUES ('Los viajes de Gulliver','Jonathan Swift',85,12);
INSERT INTO books (name, author, pages, samples) VALUES ('Guerra y paz','Lev Tolstói',203,11);
INSERT INTO books (name, author, pages, samples) VALUES ('Ana Karenina','Lev Tolstói',185,8);
INSERT INTO books (name, author, pages, samples) VALUES ('La muerte de Iván Ilich','Lev Tolstói',140,16);
INSERT INTO books (name, author, pages, samples) VALUES ('Las aventuras de Huckleberry Finn','Mark Twain',249,10);
INSERT INTO books (name, author, pages, samples) VALUES ('Ramayana','Valmiki',155,14);
INSERT INTO books (name, author, pages, samples) VALUES ('Eneida','Virgilio',220,16);
INSERT INTO books (name, author, pages, samples) VALUES ('Mahabhárata','Viasa',279,14);
INSERT INTO books (name, author, pages, samples) VALUES ('Hojas de hierba','Walt Whitman',124,8);
INSERT INTO books (name, author, pages, samples) VALUES ('La señora Dalloway','Virginia Woolf',167,1);
INSERT INTO books (name, author, pages, samples) VALUES ('Al faro','Virginia Woolf',213,17);
INSERT INTO books (name, author, pages, samples) VALUES ('Memorias de Adriano','Marguerite Yourcenar',117,13);
INSERT INTO users (name, numero_id, phone) VALUES ('Yuriy', 'Y22233444K', '642 88 93');
INSERT INTO users (name, numero_id, phone) VALUES ('Juan', '333233444G', '666 99 00');
INSERT INTO users (name, numero_id, phone) VALUES ('Adela', '234789765H', '654 25 34');

